config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'sessions#new'

  namespace :admin do
    resources :users
    resources :rewards
  end

  namespace :user do
    resources :rewards, only: [:index, :show]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_many :user_rewards
  has_many :users, through: :user_rewards

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_rewards
  has_many :rewards, through: :user_rewards

  has_secure_password
  
  validates :name, presence: true
  validates :password, presence: true

  enum role: %w(default, admin)

  def admin?
    role == "admin"
  end
end

app/models/user_reward.rb
class UserReward < ActiveRecord::Base
  belongs_to :user
  belongs_to :reward

  validates :user_id, presence: true
  validates :reward_id, presence: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      flash[:notice] = "Reward #{@reward.name} has been created!"
      redirect_to admin_rewards_path
    else
      flash[:error] = @reward.errors.full_messages.join(", ")
    end
  end

  def index
    @rewards = Reward.all
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    if @reward.update(reward_params)
      flash[:notice] = "Reward #{@reward.name} has been updated!"
      redirect_to admin_rewards_path
    else
      flash[:notice] = @reward.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    redirect_to admin_rewards_path
  end

private
  def reward_params
    params.require(:reward).permit(:name, :description)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(name: params[:user][:name])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      flash[:error] = "Points did not update!"
      render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:points)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :current_admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:message] = "Incorrect login."
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You have successfully logged out."
    redirect_to login_path
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
end

app/controllers/user/rewards_controller.rb
class User::RewardsController < User::BaseController
  def index
    @rewards = Reward.all
  end

  def show
    @reward = Reward.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "New account created!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = "Invalid name and/or password!"
      render :new
    end
  end

  def show
    # byebug
    if current_user.admin?
      redirect_to admin_users_path
    else
      @user = current_user
      @rewards = User.all.map {|user| user.rewards}
      @user_rewards = @user.rewards
    end
  end

  def update
    reward = Reward.find(params[:user][:reward_id])
    if current_user.points >= reward.cost
      current_user.update(points: (current_user.points - reward.cost), redeemed: (current_user.redeemed + reward.cost))
      current_user.rewards << reward
      flash[:notice] = "You have purchased #{reward.name}"
      redirect_to user_path
    else
      flash[:errors] = "You don't have enough points to buy this reward!"
      redirect_to user_path
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/rewards/_form.html.erb
<%= form_for([:admin, @reward]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/admin/rewards/edit.html.erb
<%= render 'form' %>

app/views/admin/rewards/index.html.erb
<h1> Rewards: </h1>

<ul>
  <% @rewards.each do |reward| %>
    <li>
      <%= reward.name %><br>
      <%= link_to "edit", edit_admin_reward_path(reward) %>
      <%= link_to "delete", admin_reward_path(reward), method: "delete" %>
    </li>
  <% end %>
</ul>

app/views/admin/rewards/new.html.erb
<%= render 'form' %>

app/views/admin/rewards/show.html.erb
<h1><%= @reward.name %></h1>

app/views/admin/user/rewards/index.html.erb
<h1>Rewards</h1>

<% @rewards.each do |reward| %>
  <%= link_to reward.name, user_reward_path(reward) %><br>
  <%= reward.cost %> points <br>
<% end %>

app/views/admin/user/rewards/show.html.erb
<h1><%= @reward.name %></h1>

<h3>This reward costs <%= @reward.cost %> points</h3>

<%= link_to "Purchase reward", @user %>

app/views/admin/users/edit.html.erb
<h1><%= @user.name %></h1>

<%= form_for([:admin, @user]) do |f| %>
 <%= f.label :points %>
 <%= f.text_field :points %>

 <%= f.submit "Update user points" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.name %><br>
      Points: <%= user.points %><br>
      <%= link_to "Edit points", edit_admin_user_path(user)%>
    </li><br>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointBox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user == nil %>
    <li><%= link_to "Login", login_path %></li>
    <li><%= link_to "New user", new_user_path %></li>
  <% elsif current_admin? %>
    <li><%= link_to "New reward", new_admin_reward_path %></li>
    <li><%= link_to "Rewards index", admin_rewards_path  %></li>
    <li><%= link_to "Users index", admin_users_path  %></li>
    <li><%= link_to "Logout", logout_path, method: "delete" %></li>
  <% else %>
    <li><%= link_to "Browse Rewards", user_rewards_path %></li>
    <li><%= link_to "Dashboard", user_path %></li>
    <li><%= link_to "Logout", logout_path, method: "delete" %></li>
  <% end %> 

  <% flash.each do |type, message| %>
    <div class="alert flash <%= type %>">
      <%= message %>
    </div>
  <% end %>
<%= yield %>

</body>
</html>

app/views/user/rewards/index.html.erb
<h1>Rewards</h1>

<% @rewards.each do |reward| %>
  <%= link_to reward.name, user_reward_path(reward) %><br>
  <%= reward.cost %> points <br>
<% end %>

app/views/user/rewards/show.html.erb
<h1><%= @reward.name %></h1>

<h3>This reward costs <%= @reward.cost %> points</h3>

<%= link_to "Purchase reward", current_user %>

app/views/users/_form.html.erb
<h1>Create a New Account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :password %>
  <%= f.text_field :password %><br>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :password %>
  <%= f.text_field :password %><br>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.name %>!</h1>

Total points: <%= @user.points %>

<br>Your Rewards:
<ul>
  <% @user_rewards.each do |reward| %>
    <li>
      <%= reward.name %>
    </li>
  <% end %>
</ul>

<br>

Available rewards:
<ul>
  <% @rewards.each do |reward| %>
    <li>
      <%= reward.name %>
    </li>
  <% end %>
</ul>